<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>Latest</LangVersion>
        <Nullable>disable</Nullable>
        <IsPackable>false</IsPackable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\CodeBoss.Jobs.EntityFrameworkCore\src\CodeBoss.Jobs.EntityFrameworkCore\CodeBoss.Jobs.EntityFrameworkCore.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>
</Project>
